INSERT INTO `pools_attributes_select_keys` VALUES ('', 3, 1, 'philosophy');
INSERT INTO `pools_attributes_select_keys` VALUES ('', 3, 2, 'aesthetics');
INSERT INTO `pools_attributes_select_keys` VALUES ('', 3, 3, 'theory of history');
INSERT INTO `pools_attributes_select_keys` VALUES ('', 3, 4, 'history');
INSERT INTO `pools_attributes_select_keys` VALUES ('', 3, 5, 'theory of culture');
INSERT INTO `pools_attributes_select_keys` VALUES ('', 3, 6, 'theory of art');
INSERT INTO `pools_attributes_select_keys` VALUES ('', 3, 7, 'economy');
INSERT INTO `pools_attributes_select_keys` VALUES ('', 3, 8, 'gender');
INSERT INTO `pools_attributes_select_keys` VALUES ('', 3, 9, 'political economy');
INSERT INTO `pools_attributes_select_keys` VALUES ('', 3, 10, 'sociology');
INSERT INTO `pools_attributes_select_keys` VALUES ('', 3, 11, 'theory of the state');
INSERT INTO `pools_attributes_select_keys` VALUES ('', 3, 12, 'theory of faschism');
INSERT INTO `pools_attributes_select_keys` VALUES ('', 3, 13, 'psychology');
INSERT INTO `pools_attributes_select_keys` VALUES ('', 3, 14, 'psychoanalysis');
INSERT INTO `pools_attributes_select_keys` VALUES ('', 3, 15, 'repression');
INSERT INTO `pools_attributes_select_keys` VALUES ('', 3, 16, 'military');
INSERT INTO `pools_attributes_select_keys` VALUES ('', 3, 17, 'art');
INSERT INTO `pools_attributes_select_keys` VALUES ('', 3, 18, 'music');
INSERT INTO `pools_attributes_select_keys` VALUES ('', 3, 19, 'film');
INSERT INTO `pools_attributes_select_keys` VALUES ('', 3, 20, 'visual arts');
INSERT INTO `pools_attributes_select_keys` VALUES ('', 3, 21, 'kids and youth');
INSERT INTO `pools_attributes_select_keys` VALUES ('', 3, 22, 'law');
INSERT INTO `pools_attributes_select_keys` VALUES ('', 3, 23, 'religion');
INSERT INTO `pools_attributes_select_keys` VALUES ('', 3, 24, 'islam');
INSERT INTO `pools_attributes_select_keys` VALUES ('', 3, 25, 'buddhism');
INSERT INTO `pools_attributes_select_keys` VALUES ('', 3, 26, 'christian');
INSERT INTO `pools_attributes_select_keys` VALUES ('', 3, 27, 'hinduism');
INSERT INTO `pools_attributes_select_keys` VALUES ('', 3, 28, 'sects');
INSERT INTO `pools_attributes_select_keys` VALUES ('', 3, 29, 'criticism of religion');
INSERT INTO `pools_attributes_select_keys` VALUES ('', 3, 30, 'slavery');
INSERT INTO `pools_attributes_select_keys` VALUES ('', 3, 31, 'drugs');
INSERT INTO `pools_attributes_select_keys` VALUES ('', 3, 32, 'racism');
INSERT INTO `pools_attributes_select_keys` VALUES ('', 3, 33, 'anti-semitism');
INSERT INTO `pools_attributes_select_keys` VALUES ('', 3, 34, 'travel');
INSERT INTO `pools_attributes_select_keys` VALUES ('', 3, 35, 'childrens book');
INSERT INTO `pools_attributes_select_keys` VALUES ('', 3, 36, 'novel');
INSERT INTO `pools_attributes_select_keys` VALUES ('', 3, 37, 'biography');
INSERT INTO `pools_attributes_select_keys` VALUES ('', 3, 38, 'lyric');
INSERT INTO `pools_attributes_select_keys` VALUES ('', 3, 39, 'thriller');
INSERT INTO `pools_attributes_select_keys` VALUES ('', 3, 40, 'germany');
INSERT INTO `pools_attributes_select_keys` VALUES ('', 3, 41, 'prussia');
INSERT INTO `pools_attributes_select_keys` VALUES ('', 3, 42, 'habsburgian');
INSERT INTO `pools_attributes_select_keys` VALUES ('', 3, 43, 'ireland');
INSERT INTO `pools_attributes_select_keys` VALUES ('', 3, 44, 'great brittain');
INSERT INTO `pools_attributes_select_keys` VALUES ('', 3, 45, 'spain');
INSERT INTO `pools_attributes_select_keys` VALUES ('', 3, 46, 'italy');
INSERT INTO `pools_attributes_select_keys` VALUES ('', 3, 47, 'portugal');
INSERT INTO `pools_attributes_select_keys` VALUES ('', 3, 48, 'france');
INSERT INTO `pools_attributes_select_keys` VALUES ('', 3, 49, 'europe');
INSERT INTO `pools_attributes_select_keys` VALUES ('', 3, 50, 'turkey');
INSERT INTO `pools_attributes_select_keys` VALUES ('', 3, 51, 'israel/palestine');
INSERT INTO `pools_attributes_select_keys` VALUES ('', 3, 52, 'middle east');
INSERT INTO `pools_attributes_select_keys` VALUES ('', 3, 53, 'kurdistan');
INSERT INTO `pools_attributes_select_keys` VALUES ('', 3, 54, 'iran');
INSERT INTO `pools_attributes_select_keys` VALUES ('', 3, 55, 'iraq');
INSERT INTO `pools_attributes_select_keys` VALUES ('', 3, 56, 'afghanistan');
INSERT INTO `pools_attributes_select_keys` VALUES ('', 3, 57, 'india');
INSERT INTO `pools_attributes_select_keys` VALUES ('', 3, 58, 'vietnam');
INSERT INTO `pools_attributes_select_keys` VALUES ('', 3, 59, 'cambodia');
INSERT INTO `pools_attributes_select_keys` VALUES ('', 3, 60, 'korea');
INSERT INTO `pools_attributes_select_keys` VALUES ('', 3, 61, 'china');
INSERT INTO `pools_attributes_select_keys` VALUES ('', 3, 62, 'japan');
INSERT INTO `pools_attributes_select_keys` VALUES ('', 3, 63, 'asia');
INSERT INTO `pools_attributes_select_keys` VALUES ('', 3, 64, 'africa');
INSERT INTO `pools_attributes_select_keys` VALUES ('', 3, 65, 'north africa');
INSERT INTO `pools_attributes_select_keys` VALUES ('', 3, 66, 'namibia');
INSERT INTO `pools_attributes_select_keys` VALUES ('', 3, 67, 'south africa');
INSERT INTO `pools_attributes_select_keys` VALUES ('', 3, 68, 'egypt');
INSERT INTO `pools_attributes_select_keys` VALUES ('', 3, 69, 'australia');
INSERT INTO `pools_attributes_select_keys` VALUES ('', 3, 70, 'oceania');
INSERT INTO `pools_attributes_select_keys` VALUES ('', 3, 71, 'america');
INSERT INTO `pools_attributes_select_keys` VALUES ('', 3, 72, 'usa');
INSERT INTO `pools_attributes_select_keys` VALUES ('', 3, 73, 'canada');
INSERT INTO `pools_attributes_select_keys` VALUES ('', 3, 74, 'mexico');
INSERT INTO `pools_attributes_select_keys` VALUES ('', 3, 75, 'guatemala');
INSERT INTO `pools_attributes_select_keys` VALUES ('', 3, 76, 'nicaragua');
INSERT INTO `pools_attributes_select_keys` VALUES ('', 3, 77, 'caribbean');
INSERT INTO `pools_attributes_select_keys` VALUES ('', 3, 78, 'central america');
INSERT INTO `pools_attributes_select_keys` VALUES ('', 3, 79, 'cuba');
INSERT INTO `pools_attributes_select_keys` VALUES ('', 3, 80, 'colombia');
INSERT INTO `pools_attributes_select_keys` VALUES ('', 3, 81, 'el salvador');
INSERT INTO `pools_attributes_select_keys` VALUES ('', 3, 82, 'bolivia');
INSERT INTO `pools_attributes_select_keys` VALUES ('', 3, 83, 'chile');
INSERT INTO `pools_attributes_select_keys` VALUES ('', 3, 84, 'peru');
INSERT INTO `pools_attributes_select_keys` VALUES ('', 3, 85, 'argentina');
INSERT INTO `pools_attributes_select_keys` VALUES ('', 3, 86, 'brazil');
INSERT INTO `pools_attributes_select_keys` VALUES ('', 3, 87, 'south america');
INSERT INTO `pools_attributes_select_keys` VALUES ('', 3, 88, 'anarchism');
INSERT INTO `pools_attributes_select_keys` VALUES ('', 3, 89, 'early socialism');
INSERT INTO `pools_attributes_select_keys` VALUES ('', 3, 90, 'marxism');
INSERT INTO `pools_attributes_select_keys` VALUES ('', 3, 91, 'leninism');
INSERT INTO `pools_attributes_select_keys` VALUES ('', 3, 92, 'stalinism');
INSERT INTO `pools_attributes_select_keys` VALUES ('', 3, 93, 'maoism');
INSERT INTO `pools_attributes_select_keys` VALUES ('', 3, 94, 'trotzkism');
INSERT INTO `pools_attributes_select_keys` VALUES ('', 3, 95, 's.i.');
INSERT INTO `pools_attributes_select_keys` VALUES ('', 3, 96, 'feminism');
INSERT INTO `pools_attributes_select_keys` VALUES ('', 3, 97, 'critical theory');
INSERT INTO `pools_attributes_select_keys` VALUES ('', 3, 98, 'theory of the left');
INSERT INTO `pools_attributes_select_keys` VALUES ('', 3, 99, 'social movements');
INSERT INTO `pools_attributes_select_keys` VALUES ('', 3, 100, 'workers movement');
INSERT INTO `pools_attributes_select_keys` VALUES ('', 3, 101, 'womens movement');
INSERT INTO `pools_attributes_select_keys` VALUES ('', 3, 102, 'environmental movement');
INSERT INTO `pools_attributes_select_keys` VALUES ('', 3, 103, 'students movement');
INSERT INTO `pools_attributes_select_keys` VALUES ('', 3, 104, 'class struggle');
INSERT INTO `pools_attributes_select_keys` VALUES ('', 3, 105, 'prehistory');
INSERT INTO `pools_attributes_select_keys` VALUES ('', 3, 106, 'ancient world');
INSERT INTO `pools_attributes_select_keys` VALUES ('', 3, 107, 'middle ages');
INSERT INTO `pools_attributes_select_keys` VALUES ('', 3, 108, 'modern times till 1789');
INSERT INTO `pools_attributes_select_keys` VALUES ('', 3, 109, 'history of culture');
INSERT INTO `pools_attributes_select_keys` VALUES ('', 3, 110, 'history of music');
INSERT INTO `pools_attributes_select_keys` VALUES ('', 3, 111, 'history of art');
INSERT INTO `pools_attributes_select_keys` VALUES ('', 3, 112, 'history of film');
INSERT INTO `pools_attributes_select_keys` VALUES ('', 3, 113, 'history of literature');
INSERT INTO `pools_attributes_select_keys` VALUES ('', 3, 114, 'history of speech');
INSERT INTO `pools_attributes_select_keys` VALUES ('', 3, 115, 'history of technology');
INSERT INTO `pools_attributes_select_keys` VALUES ('', 3, 116, 'history of economy');
INSERT INTO `pools_attributes_select_keys` VALUES ('', 3, 117, 'military history');
INSERT INTO `pools_attributes_select_keys` VALUES ('', 3, 118, '1st world war');
INSERT INTO `pools_attributes_select_keys` VALUES ('', 3, 119, '2nd world war');
INSERT INTO `pools_attributes_select_keys` VALUES ('', 3, 120, 'history of revolutions');
INSERT INTO `pools_attributes_select_keys` VALUES ('', 3, 121, 'french revolution');
INSERT INTO `pools_attributes_select_keys` VALUES ('', 3, 122, 'russian revolution');
INSERT INTO `pools_attributes_select_keys` VALUES ('', 3, 123, '1848 revolution');
INSERT INTO `pools_attributes_select_keys` VALUES ('', 3, 124, 'paris commune');
INSERT INTO `pools_attributes_select_keys` VALUES ('', 3, 125, 'german history');
INSERT INTO `pools_attributes_select_keys` VALUES ('', 3, 126, '3rd reich');
INSERT INTO `pools_attributes_select_keys` VALUES ('', 3, 127, 'shoah');
INSERT INTO `pools_attributes_select_keys` VALUES ('', 3, 128, 'faschism');
INSERT INTO `pools_attributes_select_keys` VALUES ('', 3, 129, 'history after 1945');